\o /dev/null
\set VERBOSITY terse
set client_min_messages=WARNING;

CREATE USER abacus WITH SUPERUSER CREATEDB REPLICATION PASSWORD 'abacus';
CREATE DATABASE abacus WITH OWNER abacus;

CREATE USER vino WITH SUPERUSER CREATEDB REPLICATION PASSWORD 'vino';
CREATE DATABASE vino WITH OWNER vino;
